ENV_VAR_PREFIX = 'DDEV_E2E_ENV_'


class E2EEnvVars:
    SET_UP = 'DDEV_E2E_UP'
    TEAR_DOWN = 'DDEV_E2E_DOWN'
    PARENT_PYTHON = 'DDEV_E2E_PYTHON_PATH'
    RESULT_FILE = 'DDEV_E2E_RESULT_FILE'
    LOGS_DIR_PREFIX = 'DDEV_E2E_ENV_TEMP_DIR_DD_LOG_'


DEFAULT_DOGSTATSD_PORT = 8125
