[tool.towncrier]
directory = "changelog.d"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
underlines = ["", "", ""]
template = "changelog_template.jinja"
title_format = "## [{version}] / {project_date}"
# We automatically link to PRs, but towncrier only has an issue template so we abuse that.
issue_format = "([#{issue}](https://github.com/DataDog/integrations-core/pull/{issue}))"

# The order of entries matters! It controls the order in which changelog sections are displayed.
# https://towncrier.readthedocs.io/en/stable/configuration.html#use-a-toml-array-defined-order
[[tool.towncrier.type]]
name = "Removed"
showcontent = true

[[tool.towncrier.type]]
name = "Changed"
showcontent = true

[[tool.towncrier.type]]
name = "Security"
showcontent = true

[[tool.towncrier.type]]
name = "Deprecated"
showcontent = true

[[tool.towncrier.type]]
name = "Added"
showcontent = true

[[tool.towncrier.type]]
name = "Fixed"
showcontent = true
